version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mobtimer:
    build:
      dockerfile: Dockerfile
    environment:
      MONGO_URI: "mongodb://root:rootpassword@mongodb_container:27017?authMechanism=DEFAULT"
    ports:
      - 8080:8080
    depends_on:
      - mongodb_container

volumes:
  mongodb_data_container: